### ISSUE TITLE
ValueError Cannot run multiple SparkContexts at once during shell startup

### ISSUE THREAD

**Issue by dgtall** [sparklingpandas/sparklingpandas#136]
Hi 
I have spark 1.4.1 setup.
I just ran ./sparklingpandashell

I got the below error:

Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 1.4.1
      /_/

Using Python version 2.7.6 (default, Jun 22 2015 17:58:13)
SparkContext available as sc, SQLContext available as sqlContext.
Traceback (most recent call last):
  File "/home/alien/spark-1.4.1/python/pyspark/shell.py", line 79, in <module>
    execfile(_pythonstartup)
  File "./sparklingpandas/shell.py", line 28, in <module>
    spark_ctx = SparkContext()
  File "/home/alien/spark-1.4.1/python/pyspark/context.py", line 110, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway)
  File "/home/alien/spark-1.4.1/python/pyspark/context.py", line 245, in _ensure_initialized
    callsite.function, callsite.file, callsite.linenum))
ValueError: Cannot run multiple SparkContexts at once; existing SparkContext(app=PySparkShell, master=local[*]) created by <module> at /home/alien/spark-1.4.1/python/pyspark/shell.py:43

**Comment by holdenk** [comment]
Thanks for noticing this. It should be fixed in master (or the latest release), changed how we launch the shell. If this is still happening in v0.0.6 for you let me know :)
