### ISSUE TITLE
pip install sparklingpandas failed

### ISSUE THREAD

**Issue by messense** [sparklingpandas/sparklingpandas#45]
Error message:

```
Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/tmp/pip-build-ibiITf/SparklingPandas/setup.py", line 12, in <module>
        long_description=open('README.md').read(),
    IOError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/private/tmp/pip-build-ibiITf/SparklingPandas/setup.py", line 12, in <module>

        long_description=open('README.md').read(),

    IOError: [Errno 2] No such file or directory: 'README.md'
```

**Comment by holdenk** [comment]
Thanks for point this out, I've always pip installed from the git repo so didn't notice this. I'll merge a fix soon.

**Comment by takluyver** [comment]
I think the problem is that you have `MANIFSET.in` instead of `MANIFEST.in`.
