### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by nymoorland** [sparklingpandas/sparklingpandas#83]
Hi,
I'm getting this error message when I try to install:
```
Running setup.py (path:/tmp/pip_build_root/sparklingpandas/setup.py) egg_info for package sparklingpandas
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/sparklingpandas/setup.py", line 12, in <module>
        long_description=open('README.md').read(),
    IOError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/sparklingpandas/setup.py", line 12, in <module>

    long_description=open('README.md').read(),

IOError: [Errno 2] No such file or directory: 'README.md'


```

**Comment by fabboe** [comment]
that is a known issue: https://github.com/sparklingpandas/sparklingpandas/issues/45

**Comment by nymoorland** [comment]
This is now working for anyone who is interested.
